using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdbSharp
{
    public enum _code
    {

        _UNKNOWN = 0, 
        _MENU, 
        _SOFT_RIGHT, 
        _HOME, 
        _BACK, 
        _CALL, 
        _ENDCALL, 
        _0, 
        _1, 
        _2, 
        _3, 
        _4, 
        _5, 
        _6, 
        _7, 
        _8, 
        _9, 
        _STAR, 
        _POUND, 
        _DPAD_UP, 
        _DPAD_DOWN, 
        _DPAD_LEFT, 
        _DPAD_RIGHT, 
        _DPAD_CENTER, 
        _VOLUME_UP, 
        _VOLUME_DOWN, 
        _POWER, 
        _CAMERA, 
        _CLEAR, 
        _A, 
        _B, 
        _C, 
        _D, 
        _E, 
        _F, 
        _G, 
        _H, 
        _I, 
        _J, 
        _K, 
        _L, 
        _M, 
        _N, 
        _O, 
        _P, 
        _Q, 
        _R, 
        _S, 
        _T, 
        _U, 
        _V, 
        _W, 
        _X, 
        _Y, 
        _Z, 
        _COMMA, 
        _PERIOD, 
        _ALT_LEFT, 
        _ALT_RIGHT, 
        _SHIFT_LEFT, 
        _SHIFT_RIGHT, 
        _TAB, 
        _SPACE, 
        _SYM, 
        _EXPLORER, 
        _ENVELOPE, 
        _ENTER, 
        _DEL, 
        _GRAVE, 
        _MINUS, 
        _EQUALS, 
        _LEFT_BRACKET, 
        _RIGHT_BRACKET, 
        _BACKSLASH, 
        _SEMICOLON, 
        _APOSTROPHE, 
        _SLASH, 
        _AT, 
        _NUM, 
        _HEADSETHOOK, 
        _FOCUS, 
        _PLUS, 
        _MENU_2, 
        _NOTIFICATION, 
        _SEARCH, 
        TagLAST_KEYCODE

    }
}
