using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdbSharp
{
    public enum Keycode
    {

        UNKNOWN = 0, 
        MENU, 
        SOFT_RIGHT, 
        HOME, 
        BACK, 
        CALL, 
        ENDCALL, 
        NUM_0, 
        NUM_1, 
        NUM_2, 
        NUM_3, 
        NUM_4, 
        NUM_5, 
        NUM_6, 
        NUM_7, 
        NUM_8,
        NUM_9, 
        STAR, 
        POUND, 
        DPAD_UP, 
        DPAD_DOWN, 
        DPAD_LEFT, 
        DPAD_RIGHT, 
        DPAD_CENTER, 
        VOLUME_UP, 
        VOLUME_DOWN, 
        POWER, 
        CAMERA, 
        CLEAR, 
        A, 
        B, 
        C, 
        D, 
        E, 
        F, 
        G, 
        H, 
        I, 
        J, 
        K, 
        L, 
        M, 
        N, 
        O, 
        P, 
        Q, 
        R, 
        S, 
        T, 
        U, 
        V, 
        W, 
        X, 
        Y, 
        Z, 
        COMMA, 
        PERIOD, 
        ALT_LEFT, 
        ALT_RIGHT, 
        SHIFT_LEFT, 
        SHIFT_RIGHT, 
        TAB, 
        SPACE, 
        SYM, 
        EXPLORER, 
        ENVELOPE, 
        ENTER, 
        DEL, 
        GRAVE, 
        MINUS, 
        EQUALS, 
        LEFT_BRACKET, 
        RIGHT_BRACKET, 
        BACKSLASH, 
        SEMICOLON, 
        APOSTROPHE, 
        SLASH, 
        AT, 
        NUM, 
        HEADSETHOOK, 
        FOCUS, 
        PLUS, 
        MENU_2, 
        NOTIFICATION, 
        SEARCH, 
        LAST_KEYCODE

    }
}
